### ISSUE TITLE
What to do with wild functors?

### ISSUE THREAD

**Issue by marcbezem** [marcbezem/SnSymm#1]
A good question that has been raised: should the details about wild functors be in the paper, in an appendix, or in a separate preprint? One thing we could also do is check how much about wild functors is perhaps already formalised, but buried in the repositories. Some people will have used (and proved) the wild functoriality of Ω.

As a reminder, an example of an excruciating detail is the remark under c99b6d7c27ec5bf60d5462e13da09497beae57d0.

**Comment by nicolaikraus** [comment]
I think an appendix would be good, but whether we can publish the paper with an appendix depends on where we publish it. Not all conferences allow appendices.

**Comment by nicolaikraus** [comment]
I close this issue since we have settled for an appendix.
